version: 0.0
os: linux
files:
  - source /
    destination: /home/ec2-user/314-application
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
    timeout: 60
    runas: ec2-user